version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/egbertp/azure-keyvault-example-golang
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: go get -u github.com/mitchellh/gox
      - run: go get -u github.com/tcnksm/ghr
      - run: go get -u github.com/stevenmatthewt/semantics
      - run:
          name: install dependencies
          command: |
            dep ensure
      - run:
          name: run tests
          command: |
            go fmt ./...
            go vet ./...
      - run:
          name: cross compile
          command: |
            gox -os="linux darwin windows openbsd" -arch="amd64" -output="dist/keyvault-get-secret_{{.OS}}_{{.Arch}}"
            cd dist/ && gzip *
      - add_ssh_keys
      - run:
          name: create release
          command: |
            tag=$(semantics --output-tag)
            if [ "$tag" ]; then
              ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace $tag dist/
            else
              echo "The commit message(s) did not indicate a major/minor/patch version."
            fi

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master




    