version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/egbertp/azure-keyvault-example-golang
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: go get -u github.com/mitchellh/gox
      - run: go get -u github.com/tcnksm/ghr
      - run: go get -u github.com/stevenmatthewt/semantics
      - run:
          name: install dependencies
          command: |
            dep ensure
      - run:
          name: run tests
          command: |
            go fmt ./...
            go vet ./...
      - run:
          name: cross compile
          command: |
            BUILD_VERSION=`git describe --tags`
            COMMIT_HASH=`git rev-parse --short=8 HEAD 2>/dev/null`
            gox -ldflags "-X main.Version=$BUILD_VERSION -X main.CommitHash=$COMMIT_HASH" -os="linux darwin windows openbsd" -arch="amd64" -output="dist/keyvault-get-secret_{{.OS}}_{{.Arch}}"
            ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace `git describe --tags` dist/
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master